WMS/WMS.WebUI/Models/UnitViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WMS.WebUI.Models
{
    public class UnitViewModel
    {
        public Guid UnitId { get; set; }

        public string UnitName { get; set; }

        public string Name { get; set; }

        public string IsHaveProduct { get; set; } = "False";

        public string Quanitiy { get; set; }

        public string ProductName { get; set; }

        public string ImageUrl { get; set; }

        public string SerialNo { get; set; }

        public string modelNo { get; set; }

        public decimal Price { get; set; }

        public string Category { get; set; }

        public string Description { get; set; }
    }
}

WMS/WMS.WebUI/Controllers/UnitsController.cs
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using WMS.Models;
using WMS.Service.Interface;
using WMS.WebUI.Common;
using WMS.WebUI.Filter;

namespace WMS.WebUI.Controllers
{
    [SimpleAuthorizeAttribute]
    [SessionExpire]
    public class UnitsController : Controller
    {
        private readonly IUnitService unitService;

        public UnitsController(IUnitService unitService)
        {
            this.unitService = unitService;
        }

        // GET: Units
        public ActionResult Index()
        {
            return View(unitService.GetAll().ToList());
        }

        // GET: Units/Details/5
        public ActionResult Details(Guid? UniqueId)
        {
            if (UniqueId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Unit unit = unitService.FindBy(x => x.UniqueId == UniqueId).FirstOrDefault();
            if (unit == null)
            {
                return HttpNotFound();
            }
            return View(unit);
        }

        // GET: Units/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Units/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Unit unit)
        {
            try
            {
                unit.CreatedBy = User.Identity.Name;
                unit.CreatedDate = DateTime.Now;
                unitService.Add(unit);
                unitService.Save();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return View(unit);
            }
        }

        // GET: Units/Edit/5
        public ActionResult Edit(Guid? UniqueId)
        {
            if (UniqueId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Unit unit = unitService.FindBy(x => x.UniqueId == UniqueId).FirstOrDefault();
            if (unit == null)
            {
                return HttpNotFound();
            }
            return View(unit);
        }

        // POST: Units/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Unit unit)
        {
            if (ModelState.IsValid)
            {
                unit.UpdatedBy = User.Identity.Name;
                unit.UpdatedDate = DateTime.Now;

                unitService.Edit(unit);
                unitService.Save();
                return RedirectToAction("Index");
            }
            return View(unit);
        }

        // GET: Units/Delete/5
        public ActionResult Delete(Guid? UniqueId)
        {
            if (UniqueId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Unit unit = unitService.FindBy(x => x.UniqueId == UniqueId).FirstOrDefault();
            if (unit == null)
            {
                return HttpNotFound();
            }
            return View(unit);
        }

        // POST: Units/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid UniqueId)
        {
            Unit unit = unitService.FindBy(x => x.UniqueId == UniqueId).FirstOrDefault();

            unit.DeletedBy = User.Identity.Name;
            unit.DeletedDate = DateTime.Now;
            unitService.Delete(unit);
            unitService.Save();
            return RedirectToAction("Index");
        }
    }
}

WMS/WMS.WebUI/Views/Units/Create.cshtml
@model WMS.Models.Unit

@{
    ViewBag.Title = "Create";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="@Url.Action("Index","Units")">Unit</a></li>
    <li class="breadcrumb-item active">Create</li>
</ol>
<hr />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4 class="page-title">
            <i class="glyphicon glyphicon-plus"></i>
            Unit
        </h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a href="@Url.Action("Index", "Units")" class="btn btn-info btn-shadow">
                    Back to List
                    <span class="glyphicon glyphicon-backward" aria-hidden="true"></span>
                </a>
                <button type="submit" value="Create" class="btn btn-success btn-shadow">
                    <i class="fa fa-save"></i> Save
                </button>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WMS/WMS.WebUI/Views/Units/Delete.cshtml
@model WMS.Models.Unit

@{
    ViewBag.Title = "Delete";
}


<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="@Url.Action("Index","Units")">Unit</a></li>
    <li class="breadcrumb-item active">Delete</li>
</ol>
<hr />
<div>
    <h4 class="page-title">
        <i class="glyphicon glyphicon-trash"></i>
        Unit
    </h4>
    <hr />
    <h5>Are you sure you want to delete this?</h5>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>


    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <a href="@Url.Action("Index", "Units")" class="btn btn-info btn-shadow">
                Back to List
                <span class="glyphicon glyphicon-backward" aria-hidden="true"></span>
            </a>
            <button type="submit" value="Delete" class="btn btn-danger btn-shadow">
                <i class="glyphicon glyphicon-trash"></i>
                Delete
            </button>
        </div>
    }
</div>

WMS/WMS.WebUI/Views/Units/Details.cshtml
@model WMS.Models.Unit

@{
    ViewBag.Title = "Details";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="@Url.Action("Index","Units")">Unit</a></li>
    <li class="breadcrumb-item active">Details</li>
</ol>
<hr />

<div>
    <h4 class="page-title">
        <i class="glyphicon glyphicon-save"></i>
        Unit
    </h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
    
    </dl>
</div>
<p>
    <a href="@Url.Action("Index", "Units")" class="btn btn-info btn-shadow">
        Back to List
        <span class="glyphicon glyphicon-backward" aria-hidden="true"></span>
    </a>
    <a href="@Url.Action("Edit", "Units")?UniqueId=@Model.UniqueId" class="btn btn-warning btn-shadow">
        Edit
        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
    </a>
</p>

WMS/WMS.WebUI/Views/Units/Edit.cshtml
@model WMS.Models.Unit

@{
    ViewBag.Title = "Edit";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="@Url.Action("Index","Units")">Unit</a></li>
    <li class="breadcrumb-item active">Edit</li>
</ol>
<hr />


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4 class="page-title">
            <i class="glyphicon glyphicon-edit"></i>
            Unit
        </h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UniqueId)
        @Html.HiddenFor(model => model.CreatedBy)
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a href="@Url.Action("Index", "Units")" class="btn btn-info btn-shadow">
                    Back to List
                    <span class="glyphicon glyphicon-backward" aria-hidden="true"></span>
                </a>
                <button type="submit" value="Save" class="btn btn-warning btn-shadow">
                    <i class="fa fa-save"></i> Save
                </button>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WMS/WMS.WebUI/Views/Units/Index.cshtml
@model IEnumerable<WMS.Models.Unit>

@{
    ViewBag.Title = "Index";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="#">Master</a></li>
    <li class="breadcrumb-item active">Unit</li>
</ol>
<hr />
<h2 class="page-title">
    Manage Units
</h2>
<p>
    <a href="@Url.Action("Create", "Units")" class="btn btn-success btn-shadow">
        Create
        <span class="fa fa-plus-circle" aria-hidden="true"></span>
    </a>
</p>
<table id="Unit" class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>

                <td>
                    <div class="btn-group">
                        <button type="button" class="btn btn-danger">Action</button>
                        <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown">
                            <span class="caret"></span>
                            <span class="sr-only">Toggle Dropdown</span>
                        </button>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="@Url.Action("Edit","Units")?UniqueId=@item.UniqueId">Edit</a>
                            <a class="dropdown-item" href="@Url.Action("Details","Units")?UniqueId=@item.UniqueId">Details</a>
                            <a class="dropdown-item" href="@Url.Action("Delete","Units")?UniqueId=@item.UniqueId">Delete</a>
                        </div>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
@section scripts{
    <script>
        $(document).ready(function () {
            $('#Unit').DataTable();
        });
    </script>
}